name: Continuous Integration
on:
  push: ~
  pull_request_target: ~

jobs:
  build:
    name: Production Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Code

      - uses: actions/setup-node@v2
        name: Setup Node
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          yarn install

      - name: Compile Production Build
        run: |
          yarn build

  formatting:
    name: Code Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Code

      - uses: actions/setup-node@v2
        name: Setup Node
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          yarn install

      - name: Format Code
        run: |
          yarn prettify
          git diff --exit-code

  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Code

      - uses: actions/setup-node@v2
        name: Setup Node
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          yarn install

      - name: Check ESLint rules
        run: |
          yarn lint

  unit-tests:
    name: Unit testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Code

      - uses: actions/setup-node@v2
        name: Setup Node
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          yarn install

      - name: Run tests
        run: |
          yarn test
